config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == "user"
      User.where(name: value)
    elsif model == "book"
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_header.html.erb
<div class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 10px;">
  <% if user_signed_in? %>
    <%= form_with url: search_search_path, method: :get, local: true do |f| %>
      <%= f.text_field 'search[value]' %>
      <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
      <%= f.submit :"検索" %>
    <% end %>
  <% end %>
</div>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
      <h2>Users search for '<%= @value %>'</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Introduction</th>
          </tr>
        </thead>
        <tbody>
          <% @datas.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %>
              </td>
              <td>
                <%= link_to "#{user.name}", user_path(user.id) %>
              </td>
              <td>
                <%= user.introduction %>
              </td>
            </tr>
          <% end %>
        </tbody>
    <% elsif @model == "book" %>
      <h2>Books search for '<%= @value %>'</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @datas.each do |book| %>
            <tr>
              <td>
                <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %>
              </td>
              <td>
                <%= link_to "#{book.title}", book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>